import { NearbyService } from '../types/services.types';

export const MAIN_SERVICES: NearbyService[] = [
  {
    id: '1',
    name: 'City General Hospital',
    category: 'hospital',
    subcategory: 'Multi-Specialty Hospital',
    address: '123 Medical Center Drive, Downtown',
    distanceKm: 2.3,
    etaMin: 8,
    status: 'available',
    phone: '+1234567890',
    isVerified: true,
  },
  {
    id: '2',
    name: 'St. Mary Medical Center',
    category: 'hospital',
    subcategory: 'Emergency Care',
    address: '456 Healthcare Blvd, Medical District',
    distanceKm: 3.7,
    etaMin: 12,
    status: 'available',
    phone: '+1234567891',
  },
  {
    id: '3',
    name: 'Metro Emergency Hospital',
    category: 'hospital',
    subcategory: '24/7 Emergency',
    address: '789 Emergency Lane, Central Area',
    distanceKm: 5.1,
    etaMin: 15,
    status: 'busy',
    phone: '+1234567892',
  },
];

export const OTHER_SERVICES: NearbyService[] = [
  {
    id: 'o1',
    name: 'QuickTow Service',
    category: 'tow',
    address: '12 Tow Ave',
    distanceKm: 1.5,
    etaMin: 5,
    status: 'available',
    phone: '+1111111111',
  },
  {
    id: 'o2',
    name: 'Roadside Repair',
    category: 'repair',
    address: '707 Mechanic Road',
    distanceKm: 2.8,
    etaMin: 9,
    status: 'available',
    phone: '+2222222222',
  },
  {
    id: 'o3',
    name: '24/7 Pharmacy',
    category: 'pharmacy',
    address: '33 Pharma Street',
    distanceKm: 1.2,
    etaMin: 4,
    status: 'available',
    phone: '+3333333333',
  },
  {
    id: 'o4',
    name: 'Shell Gas Station',
    category: 'gas',
    address: '99 Fuel Road',
    distanceKm: 3.1,
    etaMin: 10,
    status: 'available',
    phone: '+4444444444',
  },
  {
    id: 'o5',
    name: 'HealthCare Clinic',
    category: 'clinic',
    address: '55 Clinic Lane',
    distanceKm: 2.5,
    etaMin: 8,
    status: 'busy',
    phone: '+5555555555',
  },
  {
    id: 'o6',
    name: 'Trauma Center',
    category: 'trauma',
    address: '200 Trauma Blvd',
    distanceKm: 4.5,
    etaMin: 14,
    status: 'available',
    phone: '+6666666666',
  },
];
